all:
	@+make debug -s -j 16 -C ./Floana-Proxy
	@+make debug -s -j 16 -C ./Leticia-Decryptor
	@+make debug -s -j 16 -C ./Plugins/GUI
	@+make debug -s -j 16 -C ./Plugins/ZoneProxy

clean:
	@+make clean -s -j 16 -C ./Floana-Proxy
	@+make clean -s -j 16 -C ./Leticia-Decryptor
	@+make clean -s -j 16 -C ./Plugins/GUI
	@+make clean -s -j 16 -C ./Plugins/ZoneProxy
